#!/usr/bin/env bash

# Stop Duplicati
docker stop duplicati
# Remove general stuff
docker system prune --force
# Remove almost all images
docker image prune -a --force
# Reinstall duplicati
run-duplicati
