#!/usr/bin/env bash

# Upgrade eclipse che first, so it handles any changes that need to be made to persistent files.
# source it so that we can use functions and variables from it here.
source /usr/local/sbin/update-che

# Stop eclipse che
cli_current stop
# Remove general stuff
docker system prune --force
# Remove almost all images
docker image prune -a --force
# Reinstall eclipse che
cli_current start
