#!/usr/bin/env bash

main() {
	ssh_perms() {
		declare homedir="$1"
		local sshdir
		sshdir="${homedir}/.ssh"
		if [[ -d "${sshdir}" ]]; then
			touch -a "${sshdir}"/{authorized_keys,known_hosts}
			chmod -R u+rwX,go-rwx "${sshdir}"/*
			chmod a+r "${sshdir}"/{authorized_keys,known_hosts}
			local pubkey
			for pubkey in "${sshdir}"/*.pub; do
				if [[ -f "${pubkey}" ]]; then # do this instead of setting nullglob
					chmod a+r "${pubkey}"
				fi
			done
		fi
	}

	restrict_to_user() {
		declare ownership="$1" directory="$2"
		chown -R "${ownership}" "${directory}"
		if [[ "$3" == "allow_group" ]]; then
			chmod -R ug+rwX,o-rwx "${directory}"
			if [[ -d "${directory}/.gnupg" ]]; then
				chmod -R g-rwx "${directory}/.gnupg"
			fi
			if [[ -d "${directory}/.zplug" ]]; then
				chmod -R g-rwx "${directory}/.zplug"
				chmod g-rwx "${directory}/.dot/l"
				chmod g-rwx "${directory}/.dot/l/zsh-custom-completion"
			fi
		else
			chmod -R go-rwx "${directory}"
		fi
		if [[ "$3" == "allow_group_x" ]]; then
			if [[ -f "${directory}/.Xauthority" ]]; then
				chmod g+rw "${directory}/.Xauthority"
			fi
		fi
	}

	homedir_perms() {
		declare homedir="$2"
		restrict_to_user $@
		ssh_perms "${homedir}"
	}

	shared_folder_perms() {
		declare directory="$1"
		restrict_to_user patricol:patrick "${directory}" allow_group
	}

	homedir_perms patricol:patrick /home/patricol allow_group_x
	homedir_perms work:patrick /home/work allow_group
	homedir_perms workmore:workmore /home/workmore
	homedir_perms root:root /root

	shared_folder_perms /home/shared

	restrict_to_user root:root /home/secure

	chown -cR root:root /usr/local/bin
	chmod -cR 755 /usr/local/bin
	chown -cR root:root /usr/local/sbin
	chmod -cR 744 /usr/local/sbin
	chmod -c 755 /usr/local/sbin

	chown -c work:patrick /media/work

	#standardnotes-desktop being installed with wrong permissions repeatedly.
	#google earth one too.
	chmod -cR a+rX /opt/*
}

main
