#!/usr/bin/env bash

main() {
	ssh_perms() {
		declare homedir="$1"
		local sshdir
		sshdir="${homedir}/.ssh"
		touch "${sshdir}"/{authorized_keys,known_hosts}
		chmod -R u+rwX,go-rwx "${sshdir}"/*
		chmod a+r "${sshdir}"/{authorized_keys,known_hosts} "${sshdir}"/*.pub
	}

	restrict_to_user() {
		declare ownership="$1" directory="$2"
		chown -R "${ownership}" "${directory}"
		if [[ "$3" == "allow_group" ]]; then
			chmod -R ug+rwX,o-rwx "${directory}"
			if [[ -d "${directory}/.zplug" ]]; then
				chmod -R g-rwx "${directory}/.zplug"
				chmod g-rwx "${directory}/.dot/l"
				chmod g-rwx "${directory}/.dot/l/zsh-custom-completion"
			fi
		else
			chmod -R go-rwx "${directory}"
		fi
	}

	homedir_perms() {
		declare homedir="$2"
		restrict_to_user $@
		ssh_perms "${homedir}"
	}

	shared_folder_perms() {
		declare directory="$1"
		restrict_to_user patricol:patrick "${directory}" allow_group
	}

	homedir_perms patricol:patrick /home/patricol
	homedir_perms root:root /root

	restrict_to_user root:root /home/secure

	chown -R root:root /usr/local/bin
	chmod -R 755 /usr/local/bin
	chown -R root:root /usr/local/sbin
	chmod -R 744 /usr/local/sbin
	chmod 755 /usr/local/sbin
}

main
