#!/usr/bin/env bash

main() {
	get_git_release_urls() {
		declare repo="$1"
		curl -s "https://api.github.com/repos/${repo}/releases/latest" | grep '"browser_download_url"' | cut -d'"' -f4
	}

	get_git_release_url() {
		declare repo="$1" filename="$2"
		get_git_release_urls "${repo}" | grep -E "/${filename}$"
	}

	get_git_release() {
		declare repo="$1" remote_filename="$2" local_filepath="$3"
		local url
		url="$(get_git_release_url "${repo}" "${remote_filename}")"
		curl -L -C - --output "${local_filepath}" "${url}"
	}

	local output_filepath
	output_filepath="/usr/local/big-bins/chectl"

	get_git_release "che-incubator/chectl" "chectl-linux" "${output_filepath}"
	chmod +x "${output_filepath}"

	unset -f get_git_release{,_url{,s}}
}

main
