#!/usr/bin/env bash

main() {
	declare command="$1"
	# valid: bootctl list | grep "id: " | cut -f2 -d':' | cut -f2 -d' '
	local target time skip_reboot
	target=""
	time="0"
	case "${command}" in
		"systemdboot"|"")
			time="60"
			;;
		"arch"|"arch-fallback"|"arch-lts"|"arch-lts-fallback"|"arch-without-extras")
			target="${command}"
			;;
		"bios")
			target="auto-reboot-to-firmware-setup"
			;;
		"rEFInd"|"refind")
			target="rEFInd"
			;;
		"reset-timeout")
			time="0"
			skip_reboot="yes"
			;;
		*)
			echo "Invalid Argument."
			exit 1
			;;
	esac

	# efivar --list | grep Loader | xargs -l1 efivar -p -n
	# efivar -n 4a67b082-0a4c-41cf-b6c7-440b29bb8c4f-LoaderConfigTimeout -w -f "/root/efivars/LoaderConfigTimeout-${time}" # Not working.

	sed -i "s/^timeout\t[0-9]*\$/timeout\t${time}/g" /boot/loader/loader.conf
	bootctl set-oneshot "${target}"

	if [[ -z "${skip_reboot}" ]]; then
		/usr/local/sbin/reboot_into "Linux Boot Manager"
	fi
}

main $@
