#!/bin/bash

sudo chattr -i /sys/firmware/efi/efivars/PreviousBoot-36d08fa7-cf0b-42f5-8f14-68df73ed3740
sudo cp /home/secure/bin_extras/PreviousBoot-Windows /sys/firmware/efi/efivars/PreviousBoot-36d08fa7-cf0b-42f5-8f14-68df73ed3740
systemctl reboot
