#!/usr/bin/env bash

main() {
	local main_dir
	main_dir="/root/info"

	pacman -Qqe | tee "${main_dir}/packages/explicit.txt" 1> /dev/null
	pacman -Qqd | tee "${main_dir}/packages/dependencies.txt" 1> /dev/null

	# use to determine if there's a discrepancy between the preset and the actual state
	systemctl list-unit-files | grep -E "\s(enabled|disabled|masked)\s" | sort | awk '{ print $2 " " $1}' | tee "${main_dir}/services.txt" 1> /dev/null
}

main
