#!/usr/bin/env bash

#first check we're connected to the internet
if ping 1.1.1.1 -c 1; then
	curl -Ls "https://archlinux.org/mirrorlist/?country=US&country=CA&protocol=https&use_mirror_status=on" | sed -e "s/^#Server/Server/" -e "/^#/d" | rankmirrors -n 50 - | tee /etc/pacman.d/mirrorlist
fi
