#!/usr/bin/env bash

#first check we're connected to the internet
if ping 1.1.1.1 -c 1; then
	curl -s "https://raw.githubusercontent.com/archlinuxarm/PKGBUILDs/master/core/pacman-mirrorlist/mirrorlist" | tee /etc/pacman.d/mirrorlist
	#curl -s "https://raw.githubusercontent.com/archlinuxarm/PKGBUILDs/master/core/pacman-mirrorlist/mirrorlist" | sed -e "s/^# Server/Server/" -e "/^#/d" | rankmirrors -n 50 - | tee /etc/pacman.d/mirrorlist
fi
