#!/usr/bin/env bash

main() {
	local upgrade_command
	upgrade_command="apm upgrade --confirm false"

	${upgrade_command}
	sudo -i -u patricol -- ${upgrade_command}
	sudo -i -u work -- ${upgrade_command}
}

main

