#!/usr/bin/env bash

main() {
	for user in patrickcp0; do
		sudo --user="${user}" -- vim +MAINTAIN
		#sudo --user="${user}" -- nvim +MAINTAIN # was running for hours and using 100% cpu usage on one core.
	done
}

main

