#!/usr/bin/env bash

main() {
	for user in patricol work; do
		sudo --login --user="${user}" -- zsh -c "source ~/.zshrc ; zplug update ; zplug clear ; autoload -U compinit ; compinit -d ~/.cache/zcompdump"
	done
	#maybe also zplug clean? that uninstalls some things that are being used, though.
}

main

