#!/usr/bin/env bash
# TODO move this to user service
main() {
	for user in patricol work; do
		sudo --user="${user}" -- zsh -c 'source ~/.zshrc ; zinit self-update; zinit update --all --parallel'
	done
}

main

