#!/usr/bin/env bash

# run vim as non-root user, to take advantage of their vimrc etc.

main() {
	if sudo -u patricol -- touch -a $@ &> /dev/null; then
		sudo -u patricol -- vim $@
	else
		env SUDO_EDITOR="vim" sudo -u patricol -- env SUDO_EDITOR="vim" sudo --edit -- $@
	fi
}

main $@
