# vi:syntax=sh
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc) for examples

SHELL="/bin/bash"

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# History options
HISTCONTROL="ignoreboth" # don't put duplicate lines or lines starting with space in the history.
shopt -s histappend # append to the history file, don't overwrite it
shopt -s cmdhist # Save multi-line commands as one command
HISTSIZE=1000
HISTFILESIZE=2000000000
PROMPT_COMMAND='history -a' # Record each line as it gets issued


[[ "${DISPLAY}" ]] && shopt -s checkwinsize # check the window size after each command and, if necessary, update the values of LINES and COLUMNS.

shopt -s autocd # cd automatically if dir is entered
#shopt -s dirspell # Correct spelling errors during tab-completion
#shopt -s cdspell # Correct spelling errors in arguments supplied to cd


PROMPT_DIRTRIM=2 # Automatically trim long paths in the prompt


bind "set completion-ignore-case on" # Perform file completion in a case insensitive fashion
#bind "set completion-map-case on" # Treat hyphens and underscores as equivalent
bind "set show-all-if-ambiguous on" # Display matches for ambiguous patterns at first tab press
bind "set mark-symlinked-directories on" # Immediately add a trailing slash when autocompleting symlinks to directories


# Enable incremental history search with up/down arrows (also Readline goodness)
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

#shopt -s globsta # If set, the pattern "**" used in a pathname expansion context will match all files and zero or more directories and subdirectories.


PS1='[\u@\h \W]\$ '

# set the title if using xterm
case "${TERM}" in
	xterm*|rxvt*)
		PS1="\[\e]0;\u@\h: \w\a\]${PS1}"
		;;
	*)	;;
esac

# enable color support for ls
if [[ -x /usr/bin/dircolors ]]; then
	[[ -r ~/.dircolors ]] && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# enable programmable completion features
if ! shopt -oq posix; then
	if [[ -f /usr/share/bash-completion/bash_completion ]]; then
		source /usr/share/bash-completion/bash_completion
	elif [[ -f /etc/bash_completion ]]; then
		source /etc/bash_completion
	fi
fi

source /usr/share/doc/pkgfile/command-not-found.bash

# Alias definitions.
if [[ -d ~/.dot/aliases/ ]]; then
	for alias_file in ~/.dot/aliases/*; do
		source "${alias_file}"
	done
	unset alias_file
fi


export EDITOR="vim"

# okay to use powerline
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
source /usr/share/powerline/bindings/bash/powerline.sh
LANG="en_US.UTF-8" powerline-daemon -q # need to start powerline-daemon with unicode LANG regardless


stty -ixon # disable Ctrl-S
